### ISSUE TITLE
Add a Lualine theme

### ISSUE THREAD

**Issue by mrjones2014** [Pocco81/Catppuccino.nvim#1]
Lualine is one of the most popular status line plugins, and lots of color schemes also offer themes for Lualine.

This theme looks really, really great btw.

**Comment by Pocco81** [comment]
> This theme looks really, really great btw.

 Thanks, I appreciate it! More theme flavors are coming out soon btw, most notably a light theme and a neon theme.

> Lualine is one of the most popular status line plugins

Yep, will definitely do.

**Comment by Pocco81** [comment]
149dcfe2ee0644bfe0be807bcc61d97f2422d39f adds this. Information about usage will be available after I officially release it, however since you are a `lualine` user you should already know how to use it. cheers :)
