### ISSUE TITLE
git diffs blend in the background in lualine

### ISSUE THREAD

**Issue by ashincoder** [Pocco81/Catppuccino.nvim#15]
Hi @Pocco81 . 
I absolutely love this theme.
But one thing that concerned me was  after editing a file there would be some diffs right. So the count of the diffs are blended to background in lualine.
Here is the screenshot: 
![2021-08-28-171202_510x85_scrot](https://user-images.githubusercontent.com/83629316/131216756-5bc5ade4-76a2-4194-8774-f2ac93cb53e0.png)

**Comment by ashincoder** [comment]
and also could u make the todo comments more bold. It would be a nice touch.. :smile:

**Comment by Pocco81** [comment]
If you want pretty TODO comments then I'd recommend ya [todo-comments.nvim](https://github.com/folke/todo-comments.nvim) . They looks very cool:

![image](https://user-images.githubusercontent.com/58336662/131228311-b45a55b7-2a73-4106-b9e0-0ba99fc0dba7.png)

**Comment by ashincoder** [comment]
That's enough. I just want the todo comments bolder. That's it thank you.

**Comment by Pocco81** [comment]
Wait so you don't want the diffs in lualine to be more visible? I think I'm still gonna do this...

**Comment by ashincoder** [comment]
I want it visible. But it's too blended in the lualine.

**Comment by ashincoder** [comment]
I can't see it properly

**Comment by Pocco81** [comment]
Looking good now:

![image](https://user-images.githubusercontent.com/58336662/131256656-1d5e2e75-b7b1-4c95-a1c5-22bf9b4f49a3.png)

**Comment by ashincoder** [comment]
yes
it does :+1:

**Comment by Pocco81** [comment]
This issue made realize that I was handling diffs and git stuff differently although they both reflect the same thing: changes in a file. So I ended up refactoring that part and this is how it looks with various integrations enabled (the things in the red boxes):

![image](https://user-images.githubusercontent.com/58336662/131257443-54dfc691-72dd-42ac-a0f8-ab66e9ad4d68.png)

I still need to update the doc before this gets to main tho.

**Comment by Pocco81** [comment]
Ok it's all merged. Enojy :+1:
