### ISSUE TITLE
Regular text is unreadable

### ISSUE THREAD

**Issue by sagarc03** [Pocco81/Catppuccino.nvim#16]
![image](https://user-images.githubusercontent.com/25496917/131397332-bd282734-021c-4d97-a1e8-dd0b89651eb8.png)

is this something i can change?

**Comment by sagarc03** [comment]
Turns out there was a overlap from another plugin, sorry for then noise.

**Comment by Pocco81** [comment]
No worries. Actually, could you tell me which plugin was it? It might be good to add something like a FAQ about it.
