### ISSUE TITLE
Gitsigns Backgrounds Sometimes Not Transparent

### ISSUE THREAD

**Issue by JBlocklove** [Pocco81/Catppuccino.nvim#17]
Sort of just what the title says. Depending on which colorscheme within catppuccino I use, the background for the gitsigns aren't transparent.

If I set it to `dark_catppuccino` only the git delete highlights aren't transparent:
![1630402575](https://user-images.githubusercontent.com/24708457/131480052-4744a231-c8ec-4f77-bab8-5a2014830e0e.png)

If I set it to `catppuccino` none of them have transparent backgrounds:
![1630402597](https://user-images.githubusercontent.com/24708457/131480061-7c6d926e-be80-4cd8-8641-6336e0da8776.png)

Any idea how I can fix this, even if it's just setting a custom color for my instance?

**Comment by Pocco81** [comment]
I think this is an issue with Catppuccino. Could you pass me the hi groups for your transparent number-line? That way I can verify the issue and fix it :)

**Comment by JBlocklove** [comment]
I have this block that I think should make most backgrounds transparent:
```lua
vim.cmd "au ColorScheme * hi Normal ctermbg=none guibg=none"
vim.cmd "au ColorScheme * hi SignColumn ctermbg=none guibg=none"
vim.cmd "au ColorScheme * hi NormalNC ctermbg=none guibg=none"
vim.cmd "au ColorScheme * hi MsgArea ctermbg=none guibg=none"
vim.cmd "au ColorScheme * hi TelescopeBorder ctermbg=none guibg=none"
vim.cmd "au ColorScheme * hi NvimTreeNormal ctermbg=none guibg=none"
```

**Comment by Pocco81** [comment]
Should be working now :)
