### ISSUE TITLE
Add Soft Manilo theme

### ISSUE THREAD

**Issue by mrjones2014** [Pocco81/Catppuccino.nvim#18]
I'd like to add a "soft Manilo" theme, similar to the dark catppuccino theme but primarily with a softer dark gray background.

**Comment by mrjones2014** [comment]
I'll submit a PR for this.

**Comment by mrjones2014** [comment]
actually, this is overkill. I can get the theme I want with minimal customization of the dark catppuccino theme.

**Comment by Pocco81** [comment]
You mind sharing how it looks?

**Comment by mrjones2014** [comment]
![image](https://user-images.githubusercontent.com/8648891/131507975-78e76ed7-b00e-4179-89b8-01e3bf5ba1b8.png)

**Comment by Pocco81** [comment]
I love it, but the color of everything else looks too sharp (text, functions, the blues). Make the PR and we will improve it :)

Some ideas:
+ Decrease saturation
+ Make all colors draw to one color (in this case brown, I suppose)
