### ISSUE TITLE
I like this project!

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#21]
I like the details you've put on this color scheme, from documentation to flexibility in configs. Did you grab a template or fork some other project to get started with this one? I'd like to make my own color scheme in the future :p thanks!

**Comment by Pocco81** [comment]
Aww thanks, I really appreciate it :) 

> Did you grab a template or fork some other project to get started with this one?

+ The base color palette? no, that's original. Like most programmers, I really loved Base16, One Dark, Atom Dark, Gruvbox, pastel colors in general and GitHub's dark theme, so they really shaped my view on how I like my colors ;)
+ The colorscheme? I learned about syntax highlighting and stuff from [norcalli/nvim-base16.nvim](https://github.com/norcalli/nvim-base16.lua), [which I forked](https://github.com/Pocco81/Base16.nvim) and added what best worked for me. I used that "theme" (so to speak) for most of my time using neovim. It really taught me which highlight groups are the main.
+ The integrations? Well I have this project in my dots called [NvDope](TheSupercalifragilisticexpialidociousDots), which has the ability to [overwrite groups to your like](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/main/.config/nvim/lua/nvd_settings.lua#L481-L574) after all the plugins and important stuff has loaded, like a run level program. I implemented the same thing here.

But what really gave me  a pin point to start from was [folke/tokyonight.nvim](https://github.com/folke/tokyonight.nvim). I didn't exactly "fork" it, but yeah, it helped a ton.

> I'd like to make my own color scheme in the future :p thanks!

A few hours ago I added the ability to overwrite colors and highlight groups, for everything. Which means that you could quite literally create a new colors-cheme with a whole new syntax highlighting just using [Catppuccino's overwriting capabilities](https://github.com/Pocco81/Catppuccino.nvim#overwriting-colors--hi-groups).

Feel free to fork catppuccino :+1:  I think the contributors and I have done a great job at it. The structure is fairly easy to understand too:

![image](https://user-images.githubusercontent.com/58336662/131773411-d1a3bc51-990d-467c-b7c1-7a12378f6437.png)

Note: the most important files are `lua/catppuccino/core/mapper.lua` and `lua/catppuccino/utils/util.lua`. There are three main tables that hold the highlight groups: the first one is the base (neovim only stuff), the integrations, and neovim properties (e.g. term gui colors, `background`, etc). The first file merges all those tables. The second file is the one that actually _highlights the highlights_.

**Comment by LuisxSullivaN** [comment]
What a generous answer! thanks bro, I actually thought of that, that I don't need to reinvent the wheel since this plugin already provides a lot of customization. I'll check on that, for the meantime I'm enjoying your colors.
