### ISSUE TITLE
Contrast on bufferline tabs

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#22]
I activated the integration for bufferline and this is how it looks:
![image](https://user-images.githubusercontent.com/29529436/131851026-fc499102-5ad7-4d46-abe0-366518258de6.png)
I can barely notice the background of the tab among with its shape, I would expect something with more contrast like this:
![image](https://user-images.githubusercontent.com/29529436/131851307-d9f58c6e-515a-4f13-a675-ec2f0815a50e.png)
Can't we have some more contrast like that one? Although I don't know how this would affect the other flavors of the colors scheme, I'm ussing Neon Latte.

**Comment by Pocco81** [comment]
### Before:

![image](https://user-images.githubusercontent.com/58336662/131903192-220de8d6-4175-487b-9190-91b6f4162e07.png)

### After:

![image](https://user-images.githubusercontent.com/58336662/131903294-6b119d4a-f0b6-461e-8ff5-cc2a356959e8.png)

**Comment by LuisxSullivaN** [comment]
Outstanding! thanks!

**Comment by LuisxSullivaN** [comment]
@Pocco81 bro:( I don't get why mine still looks different than yours:
![image](https://user-images.githubusercontent.com/29529436/131913152-83ad1761-b509-45d2-903d-896f70ed10ee.png)

The color which I get for unactive tabs is `#0f081c` and `#150b26` for active ones. I tried deactivating my other plugins but still no luck :/ I have the integration enabled.

**Comment by Pocco81** [comment]
Hmm that's very weird...

+ May I see your config?
+ Which branch are you using?
+ Are you using ~HEAD?
+ Is this only happening with `neon_latte`?
+ Could you try this config:

```lua
local present, catppuccino = pcall(require, "catppuccino")
if not present then
	return
end

catppuccino.setup({
	colorscheme = "neon_latte",
	transparency = false,
	term_colors = false,
	styles = {
		comments = "italic",
		functions = "italic",
		keywords = "italic",
		strings = "NONE",
		variables = "NONE",
	},
	integrations = {
		treesitter = true,
		native_lsp = {
			enabled = true,
			styles = {
				errors = "italic",
				hints = "italic",
				warnings = "italic",
				information = "italic",
			},
		},
		lsp_trouble = false,
		lsp_saga = true,
		gitgutter = false,
		gitsigns = true,
		telescope = true,
		nvimtree = {
			enabled = true,
			show_root = false,
		},
		which_key = false,
		indent_blankline = true,
		dashboard = true,
		neogit = false,
		vim_sneak = false,
		fern = false,
		barbar = false,
		bufferline = true,
		markdown = true,
		lightspeed = false,
		ts_rainbow = false,
	},
})

catppuccino.load()
```

**Comment by Pocco81** [comment]
Btw which font is that? the italics look sick!

**Comment by LuisxSullivaN** [comment]
- My config:
```lua
local catppuccino = require('catppuccino')

catppuccino.setup {
   colorscheme = 'neon_latte',
   term_colors = true,
   styles = {
      comments = "italic",
      functions = "italic",
      keywords = "italic",
      strings = "italic",
      variables = "NONE",
   },
   integrations = {
      treesitter = true,
      native_lsp = {
         enabled = true,
         styles = {
            errors = "italic",
            hints = "italic",
            warnings = "italic",
            information = "italic"
         }
      },
      lsp_trouble = true,
      lsp_saga = false,
      gitgutter = false,
      gitsigns = true,
      telescope = true,
      nvimtree = {
         enabled = true,
         show_root = true,
      },
      which_key = true,
      indent_blankline = true,
      dashboard = true,
      neogit = false,
      vim_sneak = false,
      fern = false,
      barbar = false,
      bufferline = true,
      markdown = true,
      lightspeed = false,
      ts_rainbow = true
   }
}

catppuccino.load()
```
- I'm using the default branch (main)
- I updated with packer.nvim and git log says I'm on the latest commit
- How do I know that?:(
- I  also tried with dark_catppuccino and tabs seem to have very low contrast too, I can share screenshots if needed
- I put that config but still no luck

Do you think it's only happening to me?:(

**Comment by LuisxSullivaN** [comment]
@Pocco81 The font is Dank Mono, I like it a lot!

**Comment by Pocco81** [comment]
Yeah it's probably a problem on your end, not necessarily with your nvim/Catppuccino config, but rather with your terminal/multiplexer.

One of NVChad's contributors had this issue (#9), which ended up being an issue on his end because of `$TERM` not being set properly.

+ By any chance, are you using a terminal multiplexer (like Tmux)?
+ Can I see the output of `echo $TERM`
+ Which terminal are you using?

**Comment by Pocco81** [comment]
> How do I know that?:(

You mean updating? Just run `:PackerSync`.

**Comment by Pocco81** [comment]
Actually, looking at the screenshots your background looks exactly like mine and it matches the color of the active tab in bufferline.

I think the issue might be your bufferline config.  Can I see your bufferline config instead? Regardless of what your config is, remember that bufferline must be loaded before Catppuccino so that Catppuccino can overwrite its highlights.

**Comment by LuisxSullivaN** [comment]
Hey! sorry for the late replay.

Yeah I use tmux but I tried without it, so `echo $TERM` outputs `tmux-256color` with tmux and `xterm-256color` without it.

This is my bufferline config:
```lua
local api = vim.api
api.nvim_set_keymap("n", "<C-j>", "<cmd>BufferLineCyclePrev<CR>", {noremap = true, silent = true})
api.nvim_set_keymap("n", "<C-k>", "<cmd>BufferLineCycleNext<CR>", {noremap = true, silent = true})

require("bufferline").setup {
   options = {
      offsets = {
         {
            filetype = "NvimTree",
            text = "Nvim tree",
            highlight = "FileExplorer"
         }
      },
      separator_style = 'slant'
   }
}
vim.cmd("hi FileExplorer gui=bold,italic")
```
I tried removing all of those options and just letting `require('bufferline').setup()` but didn't work. I use gnome-terminal, but even installed alacritty and the issue still remains:
![image](https://user-images.githubusercontent.com/29529436/132081735-75b5a63f-4fb8-44bb-a55c-06c89d853c2a.png)

> Also notice, that regardless of what your config is, remember that bufferline must be loaded before Catppuccino so that Catppuccino can overwrite its highlights.

How can I ensure this?

If it helps, [here](https://github.com/LuisxSullivaN/nvimrc) you can find all my neovim configs, including my plugins.

**Comment by LuisxSullivaN** [comment]
> You mean updating? Just run :PackerSync.

Yes, I did that.

**Comment by Pocco81** [comment]
> How can I ensure this?

[like this](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev/.config/nvim/lua/nvdope/initialization/init.lua#L35)

**Comment by Pocco81** [comment]
I'll try your setup. In the mean time, could you try the base tmux config [and optionally the colorscheme integration] [provided by Catppuccino](https://github.com/Pocco81/Catppuccino.nvim/tree/main/extra/tmux)?

**Comment by LuisxSullivaN** [comment]
Hello again bro, I tried putting that line of config with no luck. One thing I noticed though that may help to debug the issue is:

1.  Uninstall Catppucinno by removing the plugin from `lua/plugins/init.lua` and running `:PackerClean`
2. Reinstall Catppucinno by adding the plugin again, running `:PackerInstall` and immediately (without exiting neovim) run `:PackerCompile` once the repo is cloned
3. You will see the colors set on bufferline as expected by Catppuccino, but once you exit an reopen neovim they'll be gone

**Comment by LuisxSullivaN** [comment]
This is my tmux.conf:
```tmux
set -g @plugin "arcticicestudio/nord-tmux"
set -g @plugin 'tmux-plugins/tmux-battery'

# Make vim colors work
#set -g default-terminal "screen-256color"

# Enable true colors
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -as terminal-overrides ',*:Smulx=\E[4::%p1%dm'  # undercurl support
set -as terminal-overrides ',*:Setulc=\E[58::2::%p1%{65536}%/%d::%p1%{256}%/%{255}%&%d::%p1%{255}%&%d%;m'  # underscore colours - needs tmux-3.0

# Windows 1 based index and renumber them when one is closed
set -g base-index 1
set -g renumber-windows on

set -s escape-time 0
set -g mouse off

set -g status-keys vi
setw -g mode-keys vi

# Open new windows in the current working directory
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Vim-like key bindings for switching panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Resize panes with vim-like key bindings
bind -r C-h resize-pane -L 2
bind -r C-j resize-pane -D 2
bind -r C-k resize-pane -U 2
bind -r C-l resize-pane -R 2

set -g message-style bg=default,fg=blue
set -g message-command-style bg=default,fg=blue

# Panes
# set -g pane-border-status top
set -g pane-border-style fg=colour8
set -g pane-active-border-style fg=blue
# set -g pane-border-format "#{#[bold]} #{pane_current_command} "

# Battery plugin. Status icons.
set -g @batt_icon_status_charging ""
set -g @batt_icon_status_charged ""
set -g @batt_icon_charge_tier8 ''
set -g @batt_icon_charge_tier7 ''
set -g @batt_icon_charge_tier6 ''
set -g @batt_icon_charge_tier5 ''
set -g @batt_icon_charge_tier4 ''
set -g @batt_icon_charge_tier3 ''
set -g @batt_icon_charge_tier2 ''
set -g @batt_icon_charge_tier1 ''

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run -b '~/.tmux/plugins/tpm/tpm'
```

Sorry I have it a little outdated (since I don't use some stuff in there anymore) and cluttered

**Comment by LuisxSullivaN** [comment]
I just tried with the base config and neon_latte for tmux and still no changes, but, the themes are sick!! I'm staying with it!

**Comment by Pocco81** [comment]
I love them so much too! they integrate perfectly with nvim + catppuccino, which is where I spend 80% of my day on :)

**Comment by Pocco81** [comment]
Good news! I cloned your setup and indeed, the problem is in your nvim config:

Before: 

![image](https://user-images.githubusercontent.com/58336662/132110133-7111b0ec-8071-481b-a0c4-f1192b0221dd.png)

After I fixed it:

![image](https://user-images.githubusercontent.com/58336662/132110215-5f1220f5-1453-4f02-97b4-faf75dffcb34.png)

I also found some issues with the loading of `nvim-web-devicons` and `nvim-tree`. Here is the final result of my modifications:

![image](https://user-images.githubusercontent.com/58336662/132110343-c5c5fd23-fb77-412d-9382-a12b32c7c0f4.png)

(the numbers represent the order in which things are being loaded and the things in the red boxes were the "important" modifications I made)

Now, the question is, do you want me to PR it to your config or could you just copy paste? the code is actually really short:

```lua
		use({ "wbthomason/packer.nvim", event = "VimEnter" })

  use({
    "kyazdani42/nvim-web-devicons",
    after = "packer.nvim",
    config = function()
         require('plugins.devicons')
    end,
  })

   use {
      'akinsho/bufferline.nvim',
      after = "nvim-web-devicons",
      config = function()
         require('plugins.bufferline')
      end,
   }

   use {
      'Pocco81/Catppuccino.nvim',
      after = 'bufferline.nvim',
      config = function()
         require('plugins.catppuccino')
      end,
   }

   use {
      'kyazdani42/nvim-tree.lua',
      cmd = "NvimTreeToggle",
      config = function()
         require('plugins.nvimtree')
      end
   }
```

**Comment by LuisxSullivaN** [comment]
Dude, you are a beast!! Haha what was wrong with icons? I didn't even know 🤣 thank you very much, I'll give it I try when I get home.

And no worries, I'll copy paste, you've already helped me :P

**Comment by Pocco81** [comment]
> And no worries, I'll copy paste, you've already helped me :P

Btw, for the indent-blankline integration the config was updated + remember to change this: 

![image](https://user-images.githubusercontent.com/58336662/132110977-58fc38e5-cb5b-4e6f-a27b-a0bf76776ec3.png)

to this:

![image](https://user-images.githubusercontent.com/58336662/132110982-1802d31a-b9df-4e6e-8b48-9b2f8733ae7c.png)

Oh and for the fix for bufferline, if you are just gonna copy and paste remember to remove the repeated plugins (the ones in my comment above) below too :)

**Comment by LuisxSullivaN** [comment]
Thanks bro, actually If you still have the repo I'd appreciate if you make the PR since you did things clean already. Sorry about that.

And for Indent Blankline, I was hoping that with the integration I could completely erase that line of config and setting the integration to true would be enough🤔

**Comment by LuisxSullivaN** [comment]
Hey bro, after reading [this issue](https://github.com/akinsho/bufferline.nvim/issues/142) I understand that bufferline.nvim is no longer supporting highlight groups, if you see the guy there (siduck76) had to change his config and use a lua table instead ([see](https://github.com/NvChad/NvChad/commit/c4a8ecf47fc8217a3df7838b5d4e9849d4d23b3c)). Don't you think it'd be cleaner for this integration if Catppuccino just provides a lua table with the colors of the current integration which we can call from our bufferline.nvim config? that way we could avoid playing around with packer.nvim.
