### ISSUE TITLE
border color on window splits

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#23]
Hey! I can see there's no border when splitting windows:
![image](https://user-images.githubusercontent.com/29529436/131851916-c40732cf-583f-4d32-b925-b22c7eda65ea.png)
Is this intended? If so, can we have an option to activate borders? I'd personally like keyword's color (purple) as the border color for a neon fashion style, but choosing it explicitly would be great too!

**Comment by Pocco81** [comment]
> Hey! I can see there's no border when splitting windows:

There is, just not quite as visible as other elements to give a more seamless effect:

![image](https://user-images.githubusercontent.com/58336662/131885289-5ac81ba4-7b1b-4694-984e-220141ec9767.png)

> Is this intended?

yes :)

> If so, can we have an option to activate borders?

Remember that a few hours ago I introduced the new API and added the functionality for [overwriting colors and hi groups](https://github.com/Pocco81/Catppuccino.nvim#overwriting-colors--hi-groups). Following the example in the README you could setup what you want:

```lua
local cp_api = require("catppuccino.api.colors")
local err, colors = cp_api.get_colors("neon_latte")

if err.status then -- good
	catppuccino.remap({},
	{
		VertSplit = { fg = colors.magenta },
	})
end

catppuccino.load()
```

And it'll look like:

![image](https://user-images.githubusercontent.com/58336662/131886618-60f77e45-4ee2-4bc9-9c71-c0aea34c0cbb.png)

**Comment by LuisxSullivaN** [comment]
Amazing! Ok thanks now I see how this works.
