### ISSUE TITLE
[Integration] colors for indent-blankline

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#28]
Hello! Is there a way to integrate highlight colors for [indent-blankline](https://github.com/lukas-reineke/indent-blankline.nvim) through `g:indent_blankline_char_highlight_list`? like an option in the config.

**Comment by Pocco81** [comment]
Good idea! I'll add it as an optional setting for the Indent Blankline integration :)

**Comment by Pocco81** [comment]
Looking good!

![image](https://user-images.githubusercontent.com/58336662/132109722-b845988c-36a4-4eea-9c47-79fc491caddb.png)

**Comment by Pocco81** [comment]
f5e342ac172af93e1d5fc4b480db5be3613046ad resolves this.
