### ISSUE TITLE
[Feature] undercurl text for lsp diagnostics

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#29]
Hello! what about having the option to choose between underlines and undercurls for lsp diagnostics? like this:
![image](https://user-images.githubusercontent.com/29529436/132104562-d328a905-2af8-48bf-bb3a-4319a9d5bec4.png)

**Comment by Pocco81** [comment]
Good idea! I added it :) Now we all can create monstrosities like this lol:

![image](https://user-images.githubusercontent.com/58336662/132108114-35b062fc-3a6b-41ca-966a-1eb9ec1f76f4.png)

**Comment by LuisxSullivaN** [comment]
Hahaha that's hilarious, awesome!

**Comment by SpicyChickenFLY** [comment]
hi,  Is this commit ready to be synced by packer now? I can't wait to try this feature out XD
