### ISSUE TITLE
gitsigns color contrast problem 

### ISSUE THREAD

**Issue by insidersbuilt** [Pocco81/Catppuccino.nvim#3]
gitsigns has no color contrast 
![image](https://user-images.githubusercontent.com/87114084/130229210-9c927653-f829-4d8d-9e28-3c232ba68e13.png)

**Comment by Pocco81** [comment]
Do you have the integration enabled?

**Comment by Pocco81** [comment]
8809a52103296fdeb836dc3b95c72859e9833c04 fixed this.
