### ISSUE TITLE
packer.nvim: Error running config for Catppuccino.nvim: ...m/lua/catppuccino/core/integrations/indent_blankline.lua:9: attempt to index field 'indent_blankline' (a boolean value)

### ISSUE THREAD

**Issue by asher-gh** [Pocco81/Catppuccino.nvim#31]
Did `packersync` today and got this error. Was working fine before.

**Comment by Pocco81** [comment]
The configuration for indent_blankline changed, that's why:

```lua
indent_blankline = {
	enabled = false,
	colored_indent_levels = false,
},
```

But yeah I'll add a more graceful handling for exceptions like this.

**Comment by asher-gh** [comment]
Thanks a lot. Just updated the `catppuccino.lua` and now its resolved.
