### ISSUE TITLE
[Feature] Highlight operators

### ISSUE THREAD

**Issue by igorlfs** [Pocco81/Catppuccino.nvim#35]
The [tokyonight](https://github.com/folke/tokyonight.nvim) theme provides a nice integration with operators:
![image](https://user-images.githubusercontent.com/84649544/133963102-f8c5d2fb-8a81-401c-9141-5118478fee34.png)
as opposed to catpuccino's current implementation:
![image](https://user-images.githubusercontent.com/84649544/133962977-ff80fbcd-bc21-4042-b8fa-c1118779c2fe.png)
(notice the difference between `<<`, `<`, `=`, `++`, `&` and `*`)
Additionally, semicolons and comma are also highlighted, but I think that's a nitpick

**Comment by Pocco81** [comment]
First off, this was intentional, because I didn't know which color to put in order to not make the code look very colorful.

Which color would you like for those? Perhaps a pale pink? Or perhaps something more like the theme you mentioned (cyan)?

**Comment by Pocco81** [comment]
> Oh, I'm sorry if I sounded too demanding...

Oh, sorry if I sounded like I was making you sound demanding... Lol

> A pale pink sounds nice to me!

Nice! I'll test that.

**Comment by Pocco81** [comment]
Enjoy! I ended up choosing cyan :+1:

**Comment by igorlfs** [comment]
> Enjoy! I ended up choosing cyan 

It's pretty good!

**Comment by Pocco81** [comment]
Thank you :)

**Comment by LuisxSullivaN** [comment]
Hey this is awesome
