### ISSUE TITLE
[Help] Issue with stylua

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#37]
Hey! Since a few weeks I wanted to start contributing to this project by creating PR but I have an issue with rendering lua files and I think it's related to indentation with stylua, right now when I open a lua file from this project it looks like this:
![image](https://user-images.githubusercontent.com/29529436/134993431-cd96892d-987d-4002-8178-e93e93e114e5.png)
As you can see some of the text is not visible.

I just wanted to know if you are familiar with this issue. I have [editorconfig](https://github.com/editorconfig/editorconfig-vim) installed and [stylua](https://github.com/JohnnyMorganz/StyLua) via `cargo`. I'm using gnome-terminal.

Thanks!

**Comment by Pocco81** [comment]
Could you disable indent-blankline (both the plugin and the integration with Catppuccino)? O think that's the issue.

And btw, just to improve your experience with nvim. Try a GPU accelerated terminal like Alacritty  or Kitty ;)

**Comment by LuisxSullivaN** [comment]
That helped, now just these characters are displayed:
![image](https://user-images.githubusercontent.com/29529436/135012226-c31a0d99-8545-4d8b-8e7a-6cfbaddef79e.png)
May it be something in my config?

And thanks for the recommendation, I'll do that!

**Comment by Pocco81** [comment]
Those are your fillchars, that's because I use 4 spaced tabs. Similar to how you have `$` for the EOL (end of line), you can set the chars used for tabs, spaces, folds, diffs, EOB (end of buffer), ... Using the fillchars.

See `:help fillchars`.

**Comment by LuisxSullivaN** [comment]
Hey! I raised an issue on indent-blankline plugin to get a more in-depth explanation and help. [This](https://github.com/lukas-reineke/indent-blankline.nvim/issues/241) solved it.

Thanks for your help!
