### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by ashincoder** [Pocco81/Catppuccino.nvim#4]
Error detected while processing /home/ashin/.local/share/nvim/site/pack/packer/start/Catppuccino.nvim/colors/catppuccino.vim:
line   12:
E5108: Error executing lua ...acker/start/Catppuccino.nvim/lua/catppuccino/core/cs.lua:21: bad argument #1 to 'next' (table expected, got nil)

**Comment by ashincoder** [comment]
I just installed it and this appears.

**Comment by Pocco81** [comment]
Weird. It was working for me before and after the fix. I tried with  the default config, no config, remapping stuff, etc and it still works. Anyways, it should be working now. Remember you can use the defaults like so:

```lua
local present, catppuccino = pcall(require, "catppuccino")
if not present then
    return
end

catppuccino.setup()
catppuccino.load()

```

**Comment by ashincoder** [comment]
Sorry for mistrouble. My stupidity. I forgot to call it catppucino.setup()
