### ISSUE TITLE
[Integration] nvim-cmp

### ISSUE THREAD

**Issue by LuisxSullivaN** [Pocco81/Catppuccino.nvim#41]
Hello, nvim-cmp recently merged a [PR](https://github.com/hrsh7th/nvim-cmp/pull/224) for using floating windows instead of the native menu when autocompleting and introduced some highlights that are available for further customization. I think we can get a cool catppuccino floating window:D

Edit: forgot to mention, idk if you use nvim-cmp so if you think it's hard to setup for you I could post some screenshots showing different highlights, or even open a PR and then we can talk about the colors to include.

**Comment by LuisxSullivaN** [comment]
Right now it looks like this:
![image](https://user-images.githubusercontent.com/29529436/136672708-a1ac7dc1-8703-4a93-8757-b73405bdb5b4.png)

From the [docs](https://github.com/hrsh7th/nvim-cmp), we have the following highlight groups available:
`CmpItemAbbr`
The abbr field.
`CmpItemAbbrDeprecated`
The deprecated item's abbr field.
`CmpItemAbbrMatch`
The matched characters highlight.
`CmpItemAbbrMatchFuzzy`
The fuzzy matched characters highlight.
`CmpItemKind`
The kind field.
`CmpItemMenu`
The menu field.

**Comment by Pocco81** [comment]
Damn the default looks very cool! Yes I'm a cmp user, and it's an awesome tool.

Do you have any "before/after" screenshot?

> post some screenshots showing different highlights, or even open a PR and then we can talk about the colors to include

Yes!!

**Comment by Pocco81** [comment]
Resolved by #42.
