### ISSUE TITLE
[dev-remaster] katpuccinno.api.colors.get_colors() is broken

### ISSUE THREAD

**Issue by cwebster2** [Pocco81/Catppuccino.nvim#47]
The readme lists the way to get the colors for a theme as
![image](https://user-images.githubusercontent.com/5762261/139912457-05652f3e-8a11-4917-8d92-af96ab50e736.png)

This is working in main and i've been using it to modify some colors that i remap.

In the dev-remaster branch the call fails

```
E5113: Error while calling lua chunk: ...er/start/Catppuccino.nvim/lua/katppuccino/api/colors.lua:4: module 'katppuccino.core.cs' not found:
        no field package.preload['katppuccino.core.cs']
        no file './katppuccino/core/cs.lua'
```

The get_colors() function is provided by https://github.com/Pocco81/Catppuccino.nvim/blob/f90dcc9e4f860ce50d002b4cf2e0861a376f574f/lua/katppuccino/api/colors.lua#L3-L5

which depends on `katpuccinno.core.cs`, which was deleted in https://github.com/Pocco81/Catppuccino.nvim/commit/0b177ad1cba91e814ba58e5ed913e4fddfc5117d

**Comment by Pocco81** [comment]
Please don't refer to the doc on that branch, I haven't had time to actually update it... My bad :)


ef399bf should've fixed this tho. You should now be able to fetch them using:
```lua
local katppuccino = require("katppuccino.api.colors").get_colors()
```

**Comment by Pocco81** [comment]
I'll update the doc ASAP :+1:
