### ISSUE TITLE
Installing dev-remaster

### ISSUE THREAD

**Issue by parker789** [Pocco81/Catppuccino.nvim#51]
Is the README on the dev-remaster branch up to date? I'm not having any luck installing following the guides. `use "Pocco81/Catppuccin.nvim"` fails to install using packer. Should this be `use "catppuccin/catppuccin"`?

**Comment by Pocco81** [comment]
> Is the README on the dev-remaster branch up to date?

Nope, sorry :)

You are using packer right? You can install it like [this](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev/.config/nvim/lua/nvdope/initialization/init.lua#L34) and configure it like [this](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev/.config/nvim/lua/nvdope/initialization/ui/catppuccin.lua).

Note: both examples were taken from my personal config.

**Comment by parker789** [comment]
Thanks!

**Comment by LuisxSullivaN** [comment]
I'm getting `acker.nvim: Error running config for Catppuccino.nvim: /Users/luis/.config/nvim/lua/plugins/catppuccin.lua:55: Vim(lua):E5108: Error executing lua ...ker/start/Catppuccino.nvim/lua/catppuccin/utils/util.lua:120: attempt to
index local 'clrs' (a nil value)` when installing catppuccino from `dev-remaster` branch with lua `term_colors = true` :(

**Comment by LuisxSullivaN** [comment]
Also lualine theme doesn't look good:
<img width="1792" alt="Screen Shot 2021-11-08 at 21 44 12" src="https://user-images.githubusercontent.com/29529436/140858272-8702e9e5-fab0-4c19-8dd6-ea6eda74aab2.png">

**Comment by Pocco81** [comment]
@LuisxSullivaN could you open two separate issues? And if possible, with the lualine one, could you PR a fix? Thanks :)

I don't use lualine + I haven't had time to test it yet.
