### ISSUE TITLE
Cannot override tabline highlights

### ISSUE THREAD

**Issue by knpwrs** [Pocco81/Catppuccino.nvim#6]
I have the following code in my `init.lua`:

```lua
catppuccino.load()

vim.cmd('hi TabLineFill ctermfg=black ctermbg=black')
vim.cmd('hi TabLine ctermfg=white ctermbg=black')
vim.cmd('hi TabLineSel ctermfg=red ctermbg=black')
```

It seems like Catppuccino is overriding my highlight groups for this though:

```
:verbose highlight TabLineFill
TabLineFill    xxx cterm=reverse ctermfg=0 ctermbg=0 guibg=#0B1216
        Last set from anonymous :source
```

Is there a way to override the highlight groups for the tabline?

**Comment by Pocco81** [comment]
But isn't it working? Sorry I wasn't able to reproduce it. Perhaps I did something wrong?

With this config:
```lua
catppuccino.setup({colorscheme = "neon_latte"})
catppuccino.load()
```

`:hi TabLine`:
![image](https://user-images.githubusercontent.com/58336662/130546524-a862a181-5b47-418d-b353-bda39d07af80.png)

With this config:
```lua
catppuccino.setup({colorscheme = "neon_latte"})
catppuccino.load()
local cmd = vim.cmd
cmd('hi TabLine ctermfg=white ctermbg=black')
```

`:hi TabLine`:
![image](https://user-images.githubusercontent.com/58336662/130546593-91362d01-ff73-4fab-a668-79f24bf368be.png)

----

Perhaps you were expecting the words "black" and "white" to appear when running `:hi TabLine`? In case you didn't know, those numbers represent the cterm colors (see `help cterm-colors`):

![image](https://user-images.githubusercontent.com/58336662/130546791-ed6a771d-be18-4ad4-b1d8-89843a36a694.png)

**Comment by knpwrs** [comment]
Well, this is embarrassing. I shortcutted actually examining the output because my tabline no longer looks how I expect it to after I installed Catppuccino, but maybe it's unrelated?

```
:verbose highlight TabLineSel
TabLineSel     xxx cterm=bold ctermfg=9 ctermbg=0 guifg=#898E99 guibg=#3b4261
        Last set from anonymous :source
```

Notice that `ctermfg` is `9` (red) and `ctermbg` is `0` (black) for the selected tab, and yet my tabline looks like this:

![image](https://user-images.githubusercontent.com/174864/130640418-9c2d1d94-a981-4bb4-9075-cdb846690db7.png)

Before installing Catpuccino my tabline was white text on black with red text indicating the current tab, and indeed when I revert my changes to switch to Catpuccino my tabline looks like this:

![image](https://user-images.githubusercontent.com/174864/130640988-d3efb50a-d27f-4aac-82da-d5edf86a0bb9.png)


If this isn't actually an issue with Catppuccino I can close this issue. Do you know what might be going on here?

**Comment by Pocco81** [comment]
[These 3](https://github.com/Pocco81/Catppuccino.nvim/blob/main/lua/catppuccino/core/mapper.lua#L65) are the hi groups Catppuccino touches related to the TabLine.

This is not an issue. Of course the TabLine is going to look different from what you had before, how else are we gonna get a consistent theme where every UI element follows the same color palette?

I've personally never used tne built-in tab line, but I did configure its colors for Catppuccino. Just find the hi groups it's using and change them to your like.

> Before installing Catpuccino my tabline was white text on black with red text indicating the current tab

Just change the hi groups after loading catppuccino ;) I'm not sure the names of all the hi groups it takes the colors from. Keep in mind that it might be using, for instance, Normal to get the foreground...

**Comment by knpwrs** [comment]
Looks like it's the `termguicolors` that are taking effect here. I could have sworn I did `set termguicolors?` and it said `notermguicolors` but now it says `termguicolors` 😵 .

Changing my highlight groups as such took care of it:

```
vim.cmd('hi TabLineFill ctermfg=black ctermbg=black guifg=lightblack guibg=lightblack')
vim.cmd('hi TabLine ctermfg=white ctermbg=black guifg=white guibg=lightblack')
vim.cmd('hi TabLineSel ctermfg=red ctermbg=black guifg=red guibg=lightblack')
```

Thank you for Catpuccino! It's a great theme 😄 .
