### ISSUE TITLE
I don't think the nvim-tree integration is working?

### ISSUE THREAD

**Issue by mrjones2014** [Pocco81/Catppuccino.nvim#7]
How do I get sidebars such as nvim-tree to have the darker color like your screenshot? I'd also like to apply this darker color to terminal buffers and Telescope if possible.

![image](https://user-images.githubusercontent.com/8648891/130608028-a4785219-f945-43bf-a57c-8f7124af394c.png)

**Comment by mrjones2014** [comment]
I am loading it after nvim-tree though 🤔 

I load themes as the very end of my `init.lua`

**Comment by mrjones2014** [comment]
oh I see you have it actually configured in packer to load the plugin in a certain order. got it.

**Comment by mrjones2014** [comment]
that's still not working for me.

**Comment by Pocco81** [comment]
May I see your packer init?

**Comment by mrjones2014** [comment]
Yeah, I tried updating it to `  use({ 'Pocco81/Catppuccino.nvim', after = 'nvim-tree.lua' })` but it still doesn't fix it for me

**Comment by mrjones2014** [comment]
![image](https://user-images.githubusercontent.com/8648891/130615016-9790e9ab-38c8-4b9d-a7cf-be9423e9e92f.png)

**Comment by Pocco81** [comment]
> I don't think the lualine theme is loading properly either.

Once again, it's about the order of execution. I'd suggest you load it like how I'm [loading Galaxyline](https://github.com/Pocco81/TheSupercalifragilisticexpialidociousDots/blob/dev/.config/nvim/lua/nvdope/initialization/init.lua#L37).

**Comment by mrjones2014** [comment]
yeah I tried that. still not working.

**Comment by Pocco81** [comment]
Did you push to your dots?

**Comment by mrjones2014** [comment]
@Pocco81 just pushed them now if you want to take a look

**Comment by Pocco81** [comment]
Ok I'm looking at them now and it seems like you didn't lazy load anything? Please consider lazy loading nvim tree.

Also, I told you to load Catppuccino before Nvim tree, which you didn't do (or maybe you did but didn't push that?)

**Comment by Pocco81** [comment]
Also Catppuccino should be loaded before Lualine or else it won't recognize it. Perhaps I'm not being clear about what the loading order should be?

**Comment by Pocco81** [comment]
Use:

```lua
use({ 'kyazdani42/nvim-tree.lua', cmd = 'NvimTreeToggle' })

use {
            "Pocco81/Catppuccino.nvim",
            after = "nvim-tree.lua", -- becausde  catppuccino overrides highlights and not the other way around
            config = function()

-- configure Catppuccino here
-              End,
       }
```

**Comment by mrjones2014** [comment]
@Pocco81 I've updated to lazy load some stuff. and loaded in the correct order, I think. still not working. Lualine is now not loading at all.

**Comment by mrjones2014** [comment]
Ah, finally got it working! The way I was handling theme selection was messing things up.

**Comment by alex-popov-tech** [comment]
hey guys, a bit late to a party :)
here is mine:
```
local filetree = {
    -- file tree
    'kyazdani42/nvim-tree.lua',
    requires = {'kyazdani42/nvim-web-devicons'},
    config = require('plugins.nvim-tree'),
    cmd = 'NvimTreeToggle'
}
....
    {
        'catppuccin/nvim',
        as = 'catppuccin',
        config = require('plugins.catppuccin')
    },
```

and nvim-tree bg is black ( as above ) :(

tried to do all sort of things above and did not work, tried to call `setup` manually after vim started and applied colorscheme again, did not work :(

cc @Pocco81

**Comment by wavded** [comment]
Yeah something is off for me too, I use `nvim-tree` and `feline` and I loose feline and nvim_tree doesn't look right when I toggle it on. Not sure what to do, tried the suggestions in this case:
<img width="600" alt="Screen Shot 2022-01-12 at 7 01 28 PM" src="https://user-images.githubusercontent.com/26638/149247246-7f111aab-a4d0-4d83-a91d-81ba79ef8192.png">
<img width="600" alt="Screen Shot 2022-01-12 at 7 01 36 PM" src="https://user-images.githubusercontent.com/26638/149247260-0990b9ef-f47a-4d36-92e7-f4cdcbe63fe8.png">

**Comment by Pocco81** [comment]
I personally have Nvim Tree setup this way:

```lua
	use({
		"kyazdani42/nvim-tree.lua",
		cmd = "NvimTreeToggle",
		config = function()
			-- your config here
		end,
	})
```

And Catppuccin is simply loaded at startup.
